services:
  db:
    container_name: anime-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: aniflix
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5334:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: